application: wixmedia-example-gae
module: default
#application: wixprospero
#module: example

version: snapshot
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest


env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'


# appcfg.py update -v --oauth2 app-test.yaml